//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///ab
        ///ad
        ///ae
        ///ag
        ///ah
        ///ai
        ///al
        ///am
        ///an
        ///ar
        ///as
        ///at
        ///aw
        ///ax
        ///ay
        ///ba
        ///be
        ///bi
        ///bo
        ///by
        ///de
        ///do
        ///ed
        ///ef
        ///eh
        ///el
        ///em
        ///en
        ///er
        ///es
        ///et
        ///ex
        ///fa
        ///go
        ///ha
        ///he
        ///hi
        ///hm
        ///ho
        ///id
        ///if
        ///in
        ///is
        ///it
        ///jo
        ///ka
        ///la
        ///li
        ///lo
        ///ma
        ///me
        ///mi
        ///mm
        ///mo
        ///mu
        ///my
        ///na
        ///ne
        ///no
        ///nu
        ///od
        ///oe
        ///of
        ///oh
        ///om
        ///on
        ///op
        ///or
        ///os
        ///ow
        ///ox
        ///oy
        ///pa
        ///pe
        ///pi
        ///re
        ///sh
        ///si
        ///so
        ///ta
        ///ti
        ///to
        ///uh
        ///um
        ///un
        ///up
        ///us
        ///ut
        ///we
        ///wo
        ///xi
        ///xu
        ///ya
        ///ye
        ///yo
        ///aah
        ///aal
        ///aas
        ///aba
        ///abo
        ///abs
        ///aby
        ///ace
        ///act
        ///add
        ///ado
        ///ads
        ///adz
        ///aff
        ///aft
        ///aga
        ///age
        ///ago
        ///aha
        ///aid
        ///ail
        ///aim
        ///ain
        ///air
        ///ais
        ///ait [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary___Lengths {
            get {
                return ResourceManager.GetString("Dictionary___Lengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///ba
        ///da
        ///ea
        ///ga
        ///ha
        ///ia
        ///la
        ///ma
        ///na
        ///ra
        ///sa
        ///ta
        ///wa
        ///xa
        ///ya
        ///ab
        ///eb
        ///ib
        ///ob
        ///yb
        ///ed
        ///od
        ///de
        ///fe
        ///he
        ///le
        ///me
        ///ne
        ///re
        ///se
        ///te
        ///xe
        ///af
        ///og
        ///ah
        ///eh
        ///ih
        ///mh
        ///oh
        ///di
        ///fi
        ///ni
        ///si
        ///ti
        ///oj
        ///ak
        ///al
        ///il
        ///ol
        ///am
        ///em
        ///im
        ///mm
        ///om
        ///um
        ///ym
        ///an
        ///en
        ///on
        ///un
        ///do
        ///eo
        ///fo
        ///ho
        ///mo
        ///no
        ///po
        ///ro
        ///so
        ///wo
        ///xo
        ///yo
        ///ap
        ///ep
        ///ip
        ///er
        ///hs
        ///is
        ///os
        ///at
        ///it
        ///ot
        ///hu
        ///mu
        ///nu
        ///pu
        ///su
        ///tu
        ///ew
        ///ow
        ///ix
        ///ux
        ///ay
        ///ey
        ///oy
        ///haa
        ///laa
        ///saa
        ///aba
        ///oba
        ///sba
        ///yba
        ///eca
        ///tca
        ///dda
        ///oda
        ///sda
        ///zda
        ///ffa
        ///tfa
        ///aga
        ///ega
        ///oga
        ///aha
        ///dia
        ///lia
        ///mia
        ///nia
        ///ria
        ///sia
        ///tia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary___Lengths___Reverse {
            get {
                return ResourceManager.GetString("Dictionary___Lengths___Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
    }
}
